#ifndef MOLLY_M1_SIMULATION_RUNTIME_LUA_HPP
#define MOLLY_M1_SIMULATION_RUNTIME_LUA_HPP

#include "simulation/pde.hpp"
#include "simulation/runtime/commands.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

/// \file
/// AOT Lua registry, callback dispatch, and runtime lifetime
namespace clx {
struct LState;
struct LValue;
} // namespace clx

namespace m1 {

struct Scenario;
struct State;

using AotModuleOpen = clx::LValue (*)(clx::LState *);

/// One compiled Lua module and its generated open function
struct AotModule {
    // Module names are supplied by the generated AOT registry
    const char *name = nullptr;
    AotModuleOpen open = nullptr;
};

/// Modules that form one scenario bundle
struct ScenarioProgram {
    // Bundle is matched against the configured Lua directory
    const char *bundle = nullptr;
    const AotModule *modules = nullptr;
    std::size_t module_count = 0U;
    std::size_t entry = 0U;
};

// AOT registry and runtime lifetime
/// Return the registry generated by CMake
[[nodiscard]] const ScenarioProgram *
generated_scenario_programs(std::size_t &count) noexcept;

/// State retained while one compiled scenario program is active
struct ScenarioRuntime {
    // program selects static AOT code; context holds the CLX state
    const ScenarioProgram *program = nullptr;
    void *context = nullptr;
    bool native_behaviour = false;
    std::uint64_t seed = 0U;
    std::vector<bool> behaviour_types;
};

// Bundle lookup and binding
/// Find a compiled bundle without loading files at runtime
[[nodiscard]] const ScenarioProgram *
find_scenario_program(std::string_view source_directory) noexcept;
/// Create the CLX state and run the scenario setup callback
[[nodiscard]] bool prepare_scenario_program(const Scenario &scenario,
                                            State &state,
                                            ScenarioRuntime &runtime,
                                            std::string &error) noexcept;
/// Replace the query callbacks used by the next Lua invocation
[[nodiscard]] bool bind_scenario_program(ScenarioRuntime &runtime,
                                         const ScriptHost &host,
                                         std::string &error);
/// Refresh host pointers without rebuilding the CLX state
void update_scenario_program_host(ScenarioRuntime &runtime,
                                  const ScriptHost &host) noexcept;
/// Prepare and bind a compiled program for simulation
[[nodiscard]] bool setup_scenario_program(Scenario &scenario, State &state,
                                          ScenarioRuntime &runtime,
                                          std::string &error);

// Callback dispatch
/// Run one named callback and return its buffered commands
[[nodiscard]] bool invoke_scenario_program(ScenarioRuntime &runtime,
                                           ScriptCallback callback,
                                           std::uint64_t step,
                                           std::vector<ScriptCommand> &commands,
                                           std::string &error) noexcept;
/// Ask Lua for the next state of one cellular site
[[nodiscard]] bool
invoke_cell_next(ScenarioRuntime &runtime, std::uint8_t current,
                 std::uint64_t generation, std::size_t cell,
                 const std::array<std::uint8_t, 256U> &neighbours,
                 std::uint8_t &next, std::string &error) noexcept;

// PDE callback interface
/// Read one field's initial value from Lua
[[nodiscard]] bool invoke_pde_initial(ScenarioRuntime &runtime,
                                      std::size_t field, double x, double y,
                                      double &value,
                                      std::string &error) noexcept;
/// Read one field's differential operator from Lua
[[nodiscard]] bool invoke_pde_coefficients(ScenarioRuntime &runtime,
                                           std::size_t field, double x,
                                           double y,
                                           PdeCoefficients &coefficients,
                                           std::string &error) noexcept;
/// Read one boundary condition at one solver time
[[nodiscard]] bool invoke_pde_boundary(ScenarioRuntime &runtime,
                                       std::size_t field, std::uint8_t side,
                                       double coordinate, double tau,
                                       PdeBoundaryKind &kind, double &value,
                                       std::string &error) noexcept;
/// Read an optional reference sample for result checking
[[nodiscard]] bool invoke_pde_reference(ScenarioRuntime &runtime,
                                        std::size_t field, double &value,
                                        bool &present,
                                        std::string &error) noexcept;

// Teardown
/// Release CLX values held by the active program
void destroy_scenario_program(ScenarioRuntime &runtime) noexcept;

} // namespace m1

#endif
