set(HPC_EXPECTED_COMPILER_ID GNU CACHE STRING "" FORCE)
set(HPC_EXPECTED_COMPILER_MAJOR 14 CACHE STRING "" FORCE)

set(CMAKE_CXX_COMPILER g++ CACHE FILEPATH "" FORCE)
if(DEFINED ENV{CXX})
    if(NOT "$ENV{CXX}" STREQUAL "")
        set(CMAKE_CXX_COMPILER "$ENV{CXX}" CACHE FILEPATH "" FORCE)
    endif()
endif()
