set(HPC_EXPECTED_COMPILER_ID AppleClang CACHE STRING "" FORCE)
set(HPC_EXPECTED_COMPILER_MAJOR 21 CACHE STRING "" FORCE)

set(CMAKE_CXX_COMPILER clang++ CACHE FILEPATH "" FORCE)
if(DEFINED ENV{CXX})
    if(NOT "$ENV{CXX}" STREQUAL "")
        set(CMAKE_CXX_COMPILER "$ENV{CXX}" CACHE FILEPATH "" FORCE)
    endif()
endif()
