include(CheckCXXCompilerFlag)
include(CheckLinkerFlag)

function(hpc_add_supported_compile_flags target)
    foreach(flag IN LISTS ARGN)
        string(MAKE_C_IDENTIFIER "${flag}" flag_id)
        set(probe "HPC_SUPPORTS_${flag_id}")
        set(saved_required_flags "")
        if(DEFINED CMAKE_REQUIRED_FLAGS)
            set(saved_required_flags "${CMAKE_REQUIRED_FLAGS}")
        endif()
        set(CMAKE_REQUIRED_FLAGS "${saved_required_flags} -Werror")
        check_cxx_compiler_flag("${flag}" "${probe}")
        set(CMAKE_REQUIRED_FLAGS "${saved_required_flags}")

        if(${probe})
            target_compile_options("${target}" INTERFACE "${flag}")
        endif()
    endforeach()
endfunction()

function(hpc_require_compile_flag flag)
    string(MAKE_C_IDENTIFIER "${flag}" flag_id)
    set(probe "HPC_REQUIRES_${flag_id}")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    check_cxx_compiler_flag("${flag}" "${probe}")
    if(NOT ${probe})
        message(FATAL_ERROR "Required compiler flag is unavailable: ${flag}")
    endif()
endfunction()

function(hpc_require_link_flag flag)
    string(MAKE_C_IDENTIFIER "${flag}" flag_id)
    set(probe "HPC_LINK_REQUIRES_${flag_id}")
    check_linker_flag(CXX "${flag}" "${probe}")
    if(NOT ${probe})
        message(FATAL_ERROR "Required linker flag is unavailable: ${flag}")
    endif()
endfunction()
