-- Player search profiles
-- Node and depth limits cap thinking time
-- Evaluation weights define the preferences consumed by chess/rules.lua
return {
    Joe = {
        style = "stubborn defence",
        search_nodes = 1250,
        search_depth = 8,
        tactical_depth = 2,
        opening_plies = 0,
        variety = 28,
        material = 11,
        centre = 7,
        pawn_advance = 4,
        activity = 2,
        piece_safety = 14,
        piece_pressure = 8,
        knight_forks = 8,
        king_safety = 18,
        king_attack = 7,
    },
    Gina = {
        style = "methodical attack",
        search_nodes = 1650,
        search_depth = 8,
        tactical_depth = 2,
        opening_plies = 0,
        variety = 12,
        material = 10,
        centre = 9,
        pawn_advance = 6,
        activity = 4,
        piece_safety = 8,
        piece_pressure = 11,
        knight_forks = 15,
        king_safety = 12,
        king_attack = 18,
    },
    Zain = {
        style = "tactical precision",
        search_nodes = 3000,
        search_depth = 9,
        tactical_depth = 3,
        opening_plies = 0,
        variety = 3,
        material = 10,
        centre = 8,
        pawn_advance = 5,
        activity = 3,
        piece_safety = 12,
        piece_pressure = 14,
        knight_forks = 17,
        king_safety = 16,
        king_attack = 16,
    },
    Amna = {
        style = "creative complications",
        search_nodes = 1500,
        search_depth = 8,
        tactical_depth = 2,
        opening_plies = 0,
        variety = 36,
        material = 10,
        centre = 7,
        pawn_advance = 5,
        activity = 4,
        piece_safety = 8,
        piece_pressure = 12,
        knight_forks = 12,
        king_safety = 10,
        king_attack = 14,
    },
    Linh = {
        style = "patient control",
        search_nodes = 3400,
        search_depth = 9,
        tactical_depth = 3,
        opening_plies = 0,
        variety = 6,
        material = 11,
        centre = 8,
        pawn_advance = 5,
        activity = 3,
        piece_safety = 15,
        piece_pressure = 12,
        knight_forks = 14,
        king_safety = 18,
        king_attack = 13,
    },
}
